export enum AuditAction {
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  UPDATE_INVENTORY = 'UPDATE_INVENTORY',
  DELETE_PRODUCT = 'DELETE_PRODUCT',
  UPDATE_ORDER = 'UPDATE_ORDER',
  VIEW_REPORT = 'VIEW_REPORT',
}
